apiVersion: v1
kind: Namespace
metadata:
  name: fghhfghfg-prod
  labels:
    environment-id: env_124bac4c-1ed2-4704-93f3-29313e0ec5cd
    project-id: project_f8fa3353-a34e-48a2-b5dd-c5f631f8df35
    project-name: fghhfghfg
    environment-name: prod
    organization-id: org_f20c804c-ee37-4760-be90-0335c55d7f42
